#!/usr/bin/env node
'use strict';

var aggregate = require('./ndjson-aggregator.js')
var prop = process.argv[2];

var data = [];
process.stdin
  .on('data', ondata)
  .on('end', onend)
  .on('error', console.error)

function ondata(d) {
  data.push(d);
}

function nonEmpty(line) {
  return line && line.trim().length
}

function onend() {
  var lines = Buffer.concat(data)
    .toString()
    .split('\n')
    .filter(nonEmpty)

  var obj
  try {
    obj = aggregate(lines, prop)
    console.log(JSON.stringify(obj, null, 2))
  } catch(e) {
    console.error(e)
  }
}
